### ISSUE TITLE
A stray comma causes hard to understand errors

### ISSUE THREAD

**Issue by szhorvat** [igraph/stimulus#4]
A stray comma causes stimulus to throw errors which don't quite make it clear what went wrong.

Specifically, I had this invalid specification:

```
igraph_joint_degree_matrix:
    PARAMS: |-
        GRAPH graph, EDGEWEIGHTS weights=NULL,
        OUT MATRIX jdm,
        INTEGER max_out_degree=-1, INTEGER max_in_degree=-1,
    DEPS: weights ON graph
```

Notice the extra comma on the next-to-last line. I'm wondering if the error can be improved.

```
Traceback (most recent call last):
  File "/home/runner/work/igraph/igraph/interfaces/.venv/bin/stimulus", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/igraph/igraph/interfaces/.venv/lib/python3.10/site-packages/stimulus/__main__.py", line 142, in main
    generator.generate(inputs, fp)
  File "/home/runner/work/igraph/igraph/interfaces/.venv/lib/python3.10/site-packages/stimulus/generators/base.py", line 396, in generate
    self.generate_functions_block(output)
  File "/home/runner/work/igraph/igraph/interfaces/.venv/lib/python3.10/site-packages/stimulus/generators/base.py", line 250, in generate_functions_block
    self.generate_function(name, output)
  File "/home/runner/work/igraph/igraph/interfaces/.venv/lib/python3.10/site-packages/stimulus/generators/debug.py", line 83, in generate_function
    param_names = {param.name for param in func_desc.iter_parameters()}
  File "/home/runner/work/igraph/igraph/interfaces/.venv/lib/python3.10/site-packages/stimulus/model/functions.py", line 143, in iter_parameters
    return self.parameters.values()
  File "/home/runner/work/igraph/igraph/interfaces/.venv/lib/python3.10/site-packages/stimulus/model/functions.py", line 63, in parameters
    self._parameters = self._parse_parameter_specifications()
  File "/home/runner/work/igraph/igraph/interfaces/.venv/lib/python3.10/site-packages/stimulus/model/functions.py", line 256, in _parse_parameter_specifications
    specs = [ParamSpec.from_string(item) for item in params]
  File "/home/runner/work/igraph/igraph/interfaces/.venv/lib/python3.10/site-packages/stimulus/model/functions.py", line 256, in <listcomp>
    specs = [ParamSpec.from_string(item) for item in params]
  File "/home/runner/work/igraph/igraph/interfaces/.venv/lib/python3.10/site-packages/stimulus/model/parameters.py", line 105, in from_string
    parts = ["IN", parts[0]] + parts[1].split(" ", 1)
IndexError: list index out of range
```

**Comment by ntamas** [comment]
Fixed this by allowing stray commas at the end (and also at the beginning or in the middle; empty items will simply be ignored).
